AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ProjectAlias:
    Type: String
    Default: cfnGuide-AuroraSkill
    Description: >
      An alias to make physical names of stack resources more easily to attribute
    AllowedPattern: '([a-zA-Z0-9][a-zA-Z0-9-]{3,64})'
    ConstraintDescription: >
      Must be between 4 and 64 characters,
      begin with an alphanumeric character
      and contain only alphanumeric characters and hyphens
  DebugMode:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: |
      Whether the Skill should run in debug mode. Value can bei either 'true' or 'false'
  AuroraMaxCapacity:
    Type: Number
    Default: 2
    Description: The maximum capacity for Aurora auto-scaling
    MinValue: 2
  LogRetention:
    Type: Number
    Default: 1
    Description: |
      The retention period (in days) for the Lambda's Cloudwatch log group
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  LambdaTimeout:
    Type: Number
    Default: 3
    Description: The timeout for the Lambda function in seconds
    MinValue: 3
    MaxValue: 10
  LambdaMemorySize:
    Type: Number
    Default: 128
    Description: The memory size for the Lambda function in MB
    AllowedValues:
      - 128
      - 256
      - 512
      - 1024
  LambdaRuntime:
    Type: String
    Default: "nodejs12.x"
    Description: |
      The runtime environment for the Lambda function
    AllowedValues:
      - "nodejs12.x"
      - "nodejs14.x"
  LambdaHandler:
    Type: String
    Default: "index.handler"
    Description: |
      The function within your deployment package that will handle incoming requests
  SkillId:
    Type: String
  CodeBucket:
    Type: String
  CodeKey:
    Type: String
  CodeVersion:
    Type: String
Resources:
  AuroraSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub ${ProjectAlias}-secret
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
  AuroraCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername: !Sub '{{resolve:secretsmanager:${AuroraSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${AuroraSecret}::password}}'
      DBClusterIdentifier: !Sub ${ProjectAlias}-cluster
      DatabaseName: !Join
        - ''
        - - 'Fn::Transform':
            - Name: 'String'
              Parameters:
                Operation: Replace
                InputString: !Ref ProjectAlias
                Old: '-'
                New: ''
          - 'Db'
      Engine: aurora
      EngineVersion: 5.6.10a
      EngineMode: serverless
      EnableHttpEndpoint: true
      ScalingConfiguration:
        AutoPause: false
        MinCapacity: 1
        MaxCapacity: !Ref AuroraMaxCapacity
  SecretRDSInstanceAttachment:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      SecretId: !Ref AuroraSecret
      TargetId: !Ref AuroraCluster
      TargetType: AWS::RDS::DBCluster
  LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: !Sub ${ProjectAlias}-policy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: !GetAtt LambdaLogGroup.Arn
                - Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                  Resource: !Ref AuroraSecret
                - Effect: Allow
                  Action:
                    - rds-data:BatchExecuteStatement
                    - rds-data:BeginTransaction
                    - rds-data:CommitTransaction
                    - rds-data:ExecuteStatement
                    - rds-data:RollbackTransaction
                  Resource: !Join
                    - ''
                    - - !Sub "arn:${AWS::Partition}:rds:${AWS::Region}:${AWS::AccountId}:cluster:"
                      - 'Fn::Transform':
                        - Name: 'String'
                          Parameters:
                            InputString: !Ref ProjectAlias
                            Operation: Lower
                      - '-cluster'
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties: 
      LogGroupName: !Sub /aws/lambda/${ProjectAlias}-lambda
      RetentionInDays: !Ref LogRetention
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectAlias}-lambda
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
        S3ObjectVersion: !Ref CodeVersion
      Handler: !Ref LambdaHandler
      Runtime: !Ref LambdaRuntime
      Role: !GetAtt LambdaRole.Arn
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Environment: 
        Variables: 
          DEBUG_MODE: !Ref DebugMode
          PROJECT_NAME: !Ref ProjectAlias
          AURORA_SECRET_ARN: !Ref AuroraSecret
          AURORA_CLUSTER_ARN: !Join
            - ''
            - - !Sub "arn:${AWS::Partition}:rds:${AWS::Region}:${AWS::AccountId}:cluster:"
              - 'Fn::Transform':
                - Name: 'String'
                  Parameters:
                    InputString: !Ref ProjectAlias
                    Operation: Lower
              - '-cluster'
          # AURORA_DATABASE_NAME: !Sub ${ProjectAlias}Db
          AURORA_DATABASE_NAME: !Join
            - ''
            - - 'Fn::Transform':
                - Name: 'String'
                  Parameters:
                    Operation: Replace
                    InputString: !Ref ProjectAlias
                    Old: '-'
                    New: ''
              - 'Db'
  LambdaAliasDev:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LambdaFunction
      FunctionVersion: $LATEST
      Name: dev
  LambdaAliasDevEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref LambdaAliasDev
      Principal: alexa-appkit.amazon.com
      EventSourceToken: !Ref SkillId
  AuroraTableCreator:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: AuroraCluster
    Properties:
      ServiceToken: !Ref LambdaAliasDev
      Region: !Ref AWS::Region
Outputs:
  SkillEndpoint:
    Description: ARN of the Lambda 'dev' alias
    Value: !Ref LambdaAliasDev