AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ProjectAlias:
    Type: String
    Default: cfnGuide-DynamoDbSkill
    Description: >
      An alias to make physical names of stack resources more easily to attribute
    AllowedPattern: '([a-zA-Z0-9][a-zA-Z0-9-]{3,64})'
    ConstraintDescription: >
      Must be between 4 and 64 characters,
      begin with an alphanumeric character
      and contain only alphanumeric characters and hyphens
  DebugMode:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: |
      Whether the Skill should run in debug mode. Value can bei either 'true' or 'false'
  LogRetention:
    Type: Number
    Default: 1
    Description: |
      The retention period (in days) for the Lambda's Cloudwatch log group
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  DynamoDbBillingMode:
    Type: String
    Default: PAY_PER_REQUEST
    Description: >
      Billing mode for your DynamoDB table. 'PROVISIONED' is eligible for the AWS free tier,
      and will reserve at least 1 capacity unit for reading and writing. 'PAY_PER_REQUEST'
      enables on-demand scaling and billing.
    AllowedValues:
      - PROVISIONED
      - PAY_PER_REQUEST
  DynamoDbReadCapacity:
    Type: Number
    Default: 1
    Description: |
      The read capacity of the DynamoDB table. Only applies for 'PROVISIONED' billing mode.
    MinValue: 1
  DynamoDbWriteCapacity:
    Type: Number
    Default: 1
    Description: |
      The write capacity of the DynamoDB table. Only applies for 'PROVISIONED' billing mode.
    MinValue: 1
  LambdaTimeout:
    Type: Number
    Default: 3
    Description: The timeout for the Lambda function in seconds
    MinValue: 3
    MaxValue: 10
  LambdaMemorySize:
    Type: Number
    Default: 128
    Description: The memory size for the Lambda function in MB
    AllowedValues:
      - 128
      - 256
      - 512
      - 1024
  LambdaRuntime:
    Type: String
    Default: "nodejs12.x"
    Description: |
      The runtime environment for the Lambda function
    AllowedValues:
      - "nodejs12.x"
      - "nodejs14.x"
  LambdaHandler:
    Type: String
    Default: "index.handler"
    Description: |
      The function within your deployment package that will handle incoming requests
  SkillId:
    Type: String
  CodeBucket:
    Type: String
  CodeKey:
    Type: String
  CodeVersion:
    Type: String
Conditions:
  isDynamoDbProvisioned: !Equals [ !Ref DynamoDbBillingMode, PROVISIONED ]
Resources:
  LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: !Sub ${ProjectAlias}-policy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: !GetAtt LambdaLogGroup.Arn
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                    - dynamodb:UpdateItem
                  Resource: 
                    - !GetAtt DynamoDbTable.Arn
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties: 
      LogGroupName: !Sub /aws/lambda/${ProjectAlias}-lambda
      RetentionInDays: !Ref LogRetention
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub ${ProjectAlias}-table
      AttributeDefinitions: 
        - AttributeName: userId
          AttributeType: S
      BillingMode: !Ref DynamoDbBillingMode
      KeySchema: 
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput: !If
        - isDynamoDbProvisioned
        - ReadCapacityUnits: !Ref DynamoDbReadCapacity
          WriteCapacityUnits: !Ref DynamoDbWriteCapacity
        - Ref: AWS::NoValue
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectAlias}-lambda
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
        S3ObjectVersion: !Ref CodeVersion
      Handler: !Ref LambdaHandler
      Runtime: !Ref LambdaRuntime
      Role: !GetAtt LambdaRole.Arn
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Environment: 
        Variables: 
          DEBUG_MODE: !Ref DebugMode
          PROJECT_NAME: !Ref ProjectAlias
          DYNAMODB_TABLE_NAME: !Sub ${ProjectAlias}-table
  LambdaAliasDev:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LambdaFunction
      FunctionVersion: $LATEST
      Name: dev
  LambdaAliasDevEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref LambdaAliasDev
      Principal: alexa-appkit.amazon.com
      EventSourceToken: !Ref SkillId
Outputs:
  SkillEndpoint:
    Description: ARN of the Lambda 'dev' alias
    Value: !Ref LambdaAliasDev
